feat: rubiks cube sample
leanprover/lean4-samples pull request #3
Opened 2022-06-24 13:33 UTC by EdAyers

Do not merge before
- [ ] https://github.com/leanprover/vscode-lean4/pull/194
- [ ] https://github.com/leanprover/lean4/pull/1238

2022-06-28 03:56 UTC, lovettchris requested changes

2022-06-28 03:56 UTC, lovettchris commented on RubiksCube/lakefile.lean
> +  let jsFile := pkgDir / "widget/dist/rubiks.js"
This doesn't work on windows, perhaps this would be better:
```lean
  let jsFile := pkgDir / "widget" / "dist" / "rubiks.js"
  let srcFiles := inputFileTarget <| pkgDir / "widget" / "src" / "rubiks.tsx"
```

2022-06-28 03:56 UTC, lovettchris commented on WidgetsMinimal/WidgetsMinimal.lean
> +@[widgetSource]
On the version of lean you have specified in the lean-toolchain I get this error?
```
././Rubiks.lean:12:0: error: unknown attribute [widgetSource]
././Rubiks.lean:21:0: error: expected token
error: external command /home/chris/.elan/toolchains/leanprover--lean4---nightly-2022-06-21/bin/lean exited with status 1
```

2022-06-28 03:56 UTC, lovettchris commented on RubiksCube/lakefile.lean
> +  let jsFile := pkgDir / "widget/dist/rubiks.js"
Ah, the proposed change is good, but we also need this fix in lean for it to work: https://github.com/leanprover/lean4/pull/1257

2022-06-28 18:17 UTC, EdAyers commented on WidgetsMinimal/WidgetsMinimal.lean
> +@[widgetSource]
yes you need a custom version of lean at the moment

2022-06-28 18:17 UTC, EdAyers commented on WidgetsMinimal/WidgetsMinimal.lean
> +@[widgetSource]
waiting on https://github.com/leanprover/lean4/pull/1238

2022-06-29 00:34 UTC, lovettchris commented on WidgetsMinimal/WidgetsMinimal.lean
> +@[widgetSource]
Oh, ok, I have that branch of Lean built and installed, but now I get this error from `lake build`:

```
error: stdout:
.\.\Rubiks.lean:5:18: error: invalid field 'isStrLit?', the environment does not contain 'Lean.TSyntax.isStrLit?'
  str
has type
  TSyntax `str
.\.\Rubiks.lean:13:23: error: elaboration function for 'includeStr' has not been implemented
  include_str "./widget/dist/rubiks.js"
error: external command c:\Users\clovett.REDMOND\.elan\toolchains\vtec\bin\lean.exe exited with status 1
error: build failed
```

2022-06-29 16:52 UTC, EdAyers commented on WidgetsMinimal/WidgetsMinimal.lean
> +@[widgetSource]
thanks for spotting

2022-08-02 21:08 UTC, Vtec234 commented
@lovettchris this should be ready for review.

2022-08-02 21:18 UTC, lovettchris commented
> @lovettchris this should be ready for review and testing.

> LEAN_PATH=.\build\lib c:\Users\clovett\.elan\toolchains\leanprover--lean4---nightly-2022-08-01\bin\lean.exe .\.\.\Rubiks.lean -R .\.\. -o .\build\lib\Rubiks.olean -i .\build\lib\Rubiks.ilean -c .\build\ir\Rubiks.c
error: stdout:
.\.\.\Rubiks.lean:16:15: error: no such file or directory (error code: 2)
  file: .\.\.\./widget/dist/rubiks.js
.\.\.\Rubiks.lean:13:2: error: cannot evaluate code because 'sorryAx' uses 'sorry' and/or contains errors
error: external command c:\Users\clovett\.elan\toolchains\leanprover--lean4---nightly-2022-08-01\bin\lean.exe exited with status 1
error: build failed

2022-08-02 21:27 UTC, Vtec234 commented
@lovettchris unfortunately we are blocked on leanprover/lake#86 and this error will likely come up again. However please see the updated `README.md` - the new instructions are to run `lake build rubiksJs` first.

2022-08-02 21:35 UTC, lovettchris commented
> @lovettchris unfortunately we are blocked on [leanprover/lake#86](https://github.com/leanprover/lake/issues/86) and this error will likely come up again. However please see the updated `README.md` - the new instructions are to run `lake build rubiksJs` first.

```
lake build rubiksJs
> npm install    # in directory .\widget
error: no such file or directory (error code: 2)
error: build failed
```

I think the problem is that you are hard coding forward slashes in a string literal which results in an invalid path on Windows.  Can you change include_str to take a `System.FilePath` so i can write this instead: 
```
javascript:= include_str (System.FilePath.mk "." / "widget" / "dist" / "rubiks.js")
```
which generates the correct backslash path on Windows?  We then seems to have one more bug in System.FilePath where it is generating a leading 'slash' in this string ` \d%3A\Temp\lean4-samples\RubiksCube\./widget/dist/rubiks.js` - and that is also invalid on Windows.  The string should be ` d:\Temp\lean4-samples\RubiksCube\.\widget\dist\rubiks.js`...

2022-08-02 21:46 UTC, Vtec234 commented
It looks like it's failing in the `npm install` step, long before the `include_str` has any relevance. We could definitely be more correct about paths, but fwiw forward-slash paths have always worked for me on modern versions of Windows. This looks a bit like leanprover/lean4#1257.

2022-08-02 21:52 UTC, lovettchris commented
Could be related to that open issue, but it's definitely failing in the include_str, I see this in the editor:

![image](https://user-images.githubusercontent.com/18707114/182479753-ac7e63c2-14dd-4c5f-aebe-79e8b75cfcf1.png)

I also filed this new bug against lean as a reminder to complete that open PR:
https://github.com/leanprover/lean4/issues/1410

2022-08-02 22:01 UTC, lovettchris commented
Seems to work great on Linux though:

![image](https://user-images.githubusercontent.com/18707114/182481024-6f01f5ac-a52c-414f-bb61-2d12a2d8d149.png)

2022-08-02 22:08 UTC, lovettchris commented
I also verified that https://github.com/leanprover/lean4/pull/1257 fixes the NPM build problem, but not the path problem, so I still see this in the editor (on Windows):

![image](https://user-images.githubusercontent.com/18707114/182481842-1b10f11a-7ce9-4628-b8a1-8814f1b57238.png)

2022-08-02 22:28 UTC, lovettchris commented
@EdAyers can you add a link and small blurb about the sample in the top level https://github.com/EdAyers/lean4-samples/blob/rubiks/README.md ?

2022-08-03 09:43 UTC, EdAyers commented
@leodemoura could the `include_str` macro live in core?

2022-08-04 00:49 UTC, leodemoura commented
> @leodemoura could the `include_str` macro live in core?

Yes!

2022-08-04 11:27 UTC, EdAyers commented
Added here: https://github.com/leanprover/lean4/pull/1407/commits/98513fa5d6de602964167a6ebb9a6ebb571d2747

2022-08-08 22:52 UTC, lovettchris approved these changes

2022-08-08 22:52 UTC, merged